### ISSUE TITLE
i tried to run download images it in colab but it showed this error

### ISSUE THREAD

**Issue by jocker1854** [qfgaohao/pytorch-vision#196]
2024-09-18 12:04:46,761 - root - Download https://storage.googleapis.com/openimages/2018_04/class-descriptions-boxable.csv.
2024-09-18 12:04:46,851 - root - Download https://storage.googleapis.com/openimages/2018_04/train/train-annotations-bbox.csv.
2024-09-18 12:04:56,822 - root - Read annotation file /root/data/open_images/train-annotations-bbox.csv
2024-09-18 12:05:22,822 - root - train bounding boxes size: 3272
2024-09-18 12:05:22,822 - root - Approximate Image Stats: 
Traceback (most recent call last):
  File "/content/pytorch-ssd/open_images_downloader.py", line 171, in <module>
    log_counts(annotations.drop_duplicates(["ImageID", "ClassName"])["ClassName"])
  File "/content/pytorch-ssd/open_images_downloader.py", line 63, in log_counts
    for k, count in values.value_counts().iteritems():
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'

**Comment by AlanMuErDan** [comment]
This is due to the version of pandas. Just change "value_counts().iteritems()" to "values.value_counts().items()" in open_inages_downloader.py in line 63 and things will work out.
